build:
    build_starting:
        image: python:2
        commands:
            - echo "Beginning new build"
    run_tests:
        image: python:2-alpine
        commands:
            - pip install -r requirements.txt
            - python testing.py


publish:
    docker:
        repo: tominoue8334/cicd_demoapp
        tag: latest
        username: tominoue8334
        password: Apple8334!
        email: tominoue@cisco.com 

deploy:
    webhook:
        image: plugins/drone-webhook
        skip_verify: true
        method: POST
        auth:
            username: CICD1
            password: CICD1
        urls:
            - https://$$MANTL_CONTROL/marathon/v2/apps/class/tominoue8334/restart?force=true


notify:
    spark:
        image: hpreston/drone-spark
        auth_token: MjI2https://developer.ciscospark.com/getting-started.html#MmE4NTgtZDM1Yi00MGIzLTk5ZGMtNjZjYjNjMDBhMjljNTIwYzExYWEtZGJj
        roomId: Y2lzY29zcGFyazovL3VzL1JPT00vYTNhNjA4YjAtZjQyYS0xMWU2LWEwMDItMWY2MWUxNDU5ZTcy
